kind: pipeline
name: default

steps:
- name: build_server
  image: maven:3.6.1-jdk-8
  commands:
  - cd omhserver
  - mvn install
- name: build_client
  image: node:8
  commands:
  - cd omhclient
  - cp app/js/prod-env.js app/js/env.js && rm app/js/*-env.js
  - npm install && npm install -g bower && bower install --allow-root omh-web-visualizations